(function(){
  'use strict';

  window.EpsilonMakerData={
    name:'budd',
    fullName:'Budi Indra Ilham',
    role:'Developer & Maker of Epsilon',
    tagline:'Developer yang suka ngoding sambil ngopi.',
    bio:'Mantan gajian yang jago ngolah angka di Excel, sekarang bikin Epsilon — kumpulan tool kecil buat urusan harian: report kurs, QR code, screenshot website, sampai assemble template email. Suka bikin hal yang praktis, cepat, dan rapi.',
    github:'https://github.com/budife',
    instagram:'https://instagram.com/budife.psd/',
    linkedin:'https://linkedin.com/in/budifelt/',
    changes:[
      {version:'v2.1.3',date:'13 Sep 2026',title:'Polish home footer',description:'Footer home dibuat lebih clean dengan border, layout kiri-kanan, link maker yang jelas, dan social buttons compact.'},
      {version:'v2.1.2',date:'13 Sep 2026',title:'Pin home footer to viewport bottom',description:'Footer home sekarang selalu menempel di bagian bawah viewport, sementara area tools menjadi satu-satunya area scroll.'},
      {version:'v2.1.1',date:'13 Sep 2026',title:'Compact four-column home grid',description:'Home tool grid sekarang memakai 4 kolom desktop dengan card, spacing, typography, header, dan footer yang lebih compact.'},
      {version:'v2.1.0',date:'13 Sep 2026',title:'Unified home tool grid',description:'Semua tool sekarang tampil dalam satu grid tanpa tab kategori, dengan label workflow kecil dan hover card yang lebih menonjol.'},
      {version:'v2.0.0',date:'13 Sep 2026',title:'PDF Tools MVP',description:'Mengganti Image Studio dari navigasi Prepare dengan PDF Tools untuk merge PDF, reorder/remove file, rename output, dan optimasi structure tanpa rasterisasi.'},
      {version:'v1.9.13',date:'13 Sep 2026',title:'Remove board images inline',description:'Presentation Board sekarang memiliki tombol × pada setiap gambar untuk menghapus file langsung dari board sebelum export.'},
      {version:'v1.9.12',date:'13 Sep 2026',title:'Keep renamed board captions in production',description:'Nama gambar yang diedit langsung di Presentation Board sekarang tetap muncul pada hasil PNG/PDF, sementara input edit tidak ikut terekam.'},
      {version:'v1.9.11',date:'13 Sep 2026',title:'Clean editable board captions',description:'Input rename pada Presentation Board tidak lagi ikut masuk ke hasil PNG/PDF dan caption panjang sekarang wrap otomatis.'},
      {version:'v1.9.10',date:'13 Sep 2026',title:'Rename directly on board',description:'Rename label gambar sekarang dilakukan langsung di bawah setiap gambar pada Presentation Board, bukan lewat daftar terpisah.'},
      {version:'v1.9.8',date:'13 Sep 2026',title:'Complete Social Size Guide planning',description:'Menambahkan safe area per preset, usage filter, notes, favorites, copy ratio/CSS/JSON, export CSV/PNG/PDF, dan metadata review/source.'},
      {version:'v1.9.7',date:'13 Sep 2026',title:'Transparent size templates',description:'Template PNG dari Social Size Guide sekarang transparan agar bisa langsung dipakai sebagai overlay di Photoshop dan aplikasi desain.'},
      {version:'v1.9.6',date:'13 Sep 2026',title:'Social Size Guide templates',description:'Setiap size card sekarang bisa download template PNG dengan safe margin kiri/kanan/atas/bawah; format story juga menampilkan danger zone.'},
      {version:'v1.9.5',date:'13 Sep 2026',title:'Focus Social Size Guide',description:'Menghapus kategori Presentation dari Social Size Guide agar fokus pada kebutuhan platform social dan messaging.'},
      {version:'v1.9.4',date:'13 Sep 2026',title:'Simplify Social Size Guide platforms',description:'Menghapus kategori Pinterest, Email, dan Print dari Social Size Guide sesuai fokus workflow social dan messaging.'},
      {version:'v1.9.3',date:'13 Sep 2026',title:'More Social Size Guide presets',description:'Menambahkan ukuran TikTok, X/Twitter, Pinterest, Email, Print, variasi platform tambahan, alias search, dan max height yang relevan.'},
      {version:'v1.9.2',date:'13 Sep 2026',title:'Copy width and height separately',description:'Angka width dan height pada size card Social Size Guide sekarang memiliki tombol copy terpisah, dengan tanda × sebagai pemisah.'},
      {version:'v1.9.1',date:'13 Sep 2026',title:'Copy pixel size directly',description:'Angka ukuran pixel pada setiap size card di Social Size Guide sekarang bisa diklik langsung untuk menyalin ukuran.'},
      {version:'v1.9.0',date:'13 Sep 2026',title:'Social Size Guide',description:'Social Canvas diubah menjadi panduan ukuran dengan filter platform, search, copy size, Use in Image Studio, custom calculator, dan preset WA Blast dengan max height.'},
      {version:'v1.8.7',date:'13 Sep 2026',title:'Rework home category navigation',description:'Tool tabs di home diubah menjadi navigation cards dengan nomor dan nama kategori yang lebih menonjol, tetap compact dan responsive.'},
      {version:'v1.8.6',date:'13 Sep 2026',title:'Fix shade swatch labels',description:'Label HEX pada Shades & tints sekarang diposisikan di dalam swatch agar tidak terpotong.'},
      {version:'v1.8.5',date:'13 Sep 2026',title:'Give Shades & tints more room',description:'Area Shades & tints diperpanjang agar swatch dan label HEX terlihat utuh tanpa terpotong.'},
      {version:'v1.8.4',date:'13 Sep 2026',title:'Fix Shades & tints panel overflow',description:'Panel Color Picker sekarang memakai sisa tinggi viewport dengan scroll internal agar bagian Shades & tints tidak terpotong.'},
      {version:'v1.8.3',date:'13 Sep 2026',title:'Preserve minor image colors',description:'Image Palette sekarang memilih cluster yang lebih representatif agar warna kecil seperti teks merah tetap terambil, dan persentase di bawah 0,1% ditampilkan sebagai <0.1%.'},
      {version:'v1.8.2',date:'13 Sep 2026',title:'Compact visual palette output',description:'Grouping warna Image Palette diperlebar agar warna yang mirip lebih banyak bergabung dan hasil palette lebih ringkas.'},
      {version:'v1.8.1',date:'13 Sep 2026',title:'More aggressive color merging',description:'Grouping Image Palette diperlebar lagi agar warna yang secara visual mirip bergabung dan jumlah warna hasil ekstraksi lebih ringkas.'},
      {version:'v1.8.0',date:'13 Sep 2026',title:'Merge similar extracted colors',description:'Image Palette sekarang menggabungkan warna yang mirip menggunakan grouping RGB yang lebih lebar, sambil tetap menampilkan warna rata-rata dari pixel asli.'},
      {version:'v1.7.9',date:'13 Sep 2026',title:'Hide zero-percent palette colors',description:'Warna hasil ekstraksi dengan persentase 0% sekarang tidak ditampilkan agar daftar palette hanya berisi warna yang benar-benar terdeteksi.'},
      {version:'v1.7.8',date:'13 Sep 2026',title:'Complete image palette colors',description:'Image Palette sekarang menampilkan semua kelompok warna yang ditemukan tanpa batas 10 warna, dengan sample lebih detail dan persentase kemunculan.'},
      {version:'v1.7.7',date:'13 Sep 2026',title:'More precise image palette sampling',description:'Image Palette sekarang mengambil sample pixel lebih banyak, memakai warna rata-rata dari pixel asli, dan menampilkan persentase kemunculan warna.'},
      {version:'v1.7.6',date:'13 Sep 2026',title:'Compact extracted palette',description:'Kartu warna pada Image Palette dibuat lebih compact agar hingga 10 warna dominan dapat terlihat dalam satu tampilan.'},
      {version:'v1.7.5',date:'13 Sep 2026',title:'More visible extracted colors',description:'Image Palette sekarang menampilkan hingga 10 warna dominan dan swatch warna diperbaiki agar selalu terlihat.'},
      {version:'v1.7.4',date:'13 Sep 2026',title:'Generic palette image clipboard',description:'Copy as image sekarang menyalin screenshot palette sebagai image/png ke clipboard secara umum, dengan fallback download jika akses clipboard ditolak browser.'},
      {version:'v1.7.3',date:'13 Sep 2026',title:'Palette screenshot copy',description:'Copy as image sekarang mengambil screenshot langsung dari tampilan Your palette agar hasilnya bisa ditempel sebagai image ke Photoshop.'},
      {version:'v1.7.2',date:'13 Sep 2026',title:'Palette image copy compatibility',description:'Copy as image sekarang menyiapkan format PNG, HTML image, dan plain text agar lebih mudah ditempel ke Photoshop dan aplikasi desain lain.'},
      {version:'v1.7.1',date:'13 Sep 2026',title:'Color Studio image palette',description:'Color Studio sekarang bisa upload gambar, membaca warna dominan secara lokal, menampilkan HEX/RGB/HSL, dan menambahkan hasil ke palette.'},
      {version:'v1.7.0',date:'13 Sep 2026',title:'Screenshot Reference Board MVP',description:'Menambahkan board lokal untuk mengumpulkan screenshot, menyimpan source URL dan note, mengatur grid, serta export PNG/PDF.'},
      {version:'v1.6.0',date:'13 Sep 2026',title:'Typography Helper MVP',description:'Menambahkan type scale, live preview heading/body/caption, line-height, letter-spacing, converter PX/PT/MM, dan copy CSS.'},
      {version:'v1.5.0',date:'13 Sep 2026',title:'Presentation Board MVP',description:'Menambahkan board lokal untuk moodboard dan approval dengan upload banyak gambar, grid 2/3/4 kolom, judul, caption, background, gap, PNG, dan PDF export.'},
      {version:'v1.4.0',date:'13 Sep 2026',title:'Social Canvas MVP',description:'Menambahkan canvas lokal untuk preset social media, image fit, zoom, posisi, background, text overlay, serta export PNG/JPG.'},
      {version:'v1.3.0',date:'13 Sep 2026',title:'Design QA MVP',description:'Menambahkan pemeriksaan batch asset untuk dimensi, aspect ratio, format, ukuran file, nama file, status PASS/WARNING/FAIL, dan export CSV.'},
      {version:'v1.2.0',date:'13 Sep 2026',title:'Color Studio MVP',description:'Menambahkan color picker, konversi HEX/RGB/HSL, palette manual, serta generator shades dan tints lokal.'},
      {version:'v1.1.0',date:'13 Sep 2026',title:'Image Studio MVP',description:'Menambahkan tool untuk resize, convert format, mengatur quality, dan rename beberapa gambar langsung di browser.'},
      {version:'v1.0.9',date:'12 Sep 2026',title:'The Maker viewport-fit & change history',description:'Halaman maker kini fit dalam viewport, hanya daftar recent changes yang scroll, dan riwayat ditampilkan bertahap 10 item lewat View more changes.'},
      {version:'v1.0.8',date:'12 Sep 2026',title:'Viewport-first page layout',description:'Halaman maker dan halaman baru diarahkan menyesuaikan viewport monitor; scroll hanya muncul di area konten saat isi melebihi tinggi layar.'},
      {version:'v1.0.7',date:'12 Sep 2026',title:'The Maker jadi halaman utama',description:'Identitas maker di semua halaman sekarang langsung menuju /the-maker, menggantikan modal maker sebagai akses utama.'},
      {version:'v1.0.6',date:'12 Sep 2026',title:'The Maker page & project memory',description:'Menambahkan halaman profil maker, recent changes terpusat, README, CHANGELOG, MEMORY, dan aturan agar changelog selalu sinkron setelah commit.'},
      {version:'v1.0.5',date:'12 Sep 2026',title:'Screenshot flow lebih jelas',description:'Progress capture sekarang menampilkan tahapan, durasi tiap proses, total waktu, dan status koneksi Google Apps Script.'},
      {version:'v1.0.4',date:'19 Aug 2026',title:'Website Screenshot upgrade',description:'Tombol Download di samping Capture, nama file otomatis sesuai link, layout 2 kolom, dan perbaikan crop email blast HSBC.'},
      {version:'v1.0.3',date:'19 Aug 2026',title:'Template Assembler baru',description:'Gabung header, layout image, dan footer jadi satu gambar utuh dengan preview dan download PNG/JPG.'},
      {version:'v1.0.2',date:'19 Aug 2026',title:'Renaming & tidy up',description:'EGA menjadi FX Rate Daily Currency Report, footer semua page pindah ke header meet the maker, dan code dirapikan.'},
      {version:'v1.0.1',date:'18 Aug 2026',title:'QR & tools setup',description:'QR Code Generator, Website Screenshot, dan Convert Text resmi masuk ke Epsilon Toolkit.'},
      {version:'v1.0.0',date:'14 Aug 2026',title:'Epsilon lahir',description:'Toolkit pertama untuk report kurs dari Excel counter rate, di-host di GitHub Pages.'}
    ]
  };
}());
