(function(){
  'use strict';
  var picker=document.getElementById('color-picker');
  var hexInput=document.getElementById('hex-input');
  var palette=[];
  var extracted=[];
  function clamp(value){return Math.max(0,Math.min(255,Math.round(value)));}
  function hexToRgb(hex){var value=hex.replace('#','');if(value.length===3)value=value.split('').map(function(c){return c+c;}).join('');var number=parseInt(value,16);return{r:number>>16&255,g:number>>8&255,b:number&255};}
  function rgbToHex(rgb){return '#'+[rgb.r,rgb.g,rgb.b].map(function(v){return clamp(v).toString(16).padStart(2,'0');}).join('').toUpperCase();}
  function rgbToHsl(rgb){var r=rgb.r/255,g=rgb.g/255,b=rgb.b/255,max=Math.max(r,g,b),min=Math.min(r,g,b),h=0,s=0,l=(max+min)/2,d=max-min;if(d){s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4;}h/=6;}return{h:Math.round(h*360),s:Math.round(s*100),l:Math.round(l*100)};}
  function hslToRgb(h,s,l){h/=360;s/=100;l/=100;if(!s)return{r:l*255,g:l*255,b:l*255};var q=l<.5?l*(1+s):l+s-l*s,p=2*l-q,convert=function(t){if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};return{r:convert(h+1/3)*255,g:convert(h)*255,b:convert(h-1/3)*255};}
  function setColor(hex){if(!/^#[0-9a-f]{6}$/i.test(hex))return;var rgb=hexToRgb(hex),hsl=rgbToHsl(rgb);picker.value=hex.toLowerCase();hexInput.value=hex.toUpperCase();document.getElementById('rgb-value').textContent=rgb.r+', '+rgb.g+', '+rgb.b;document.getElementById('hsl-value').textContent=hsl.h+'°, '+hsl.s+'%, '+hsl.l+'%';document.getElementById('base-label').textContent=hex.toUpperCase();renderShades(rgb);}
  function renderShades(rgb){var list=document.getElementById('shade-list'),items=[];for(var i=0;i<=10;i+=1){var lightness=i*10;var color=rgbToHex(hslToRgb(rgbToHsl(rgb).h,rgbToHsl(rgb).s,lightness));items.push('<button class="shade-swatch" style="background:'+color+'" data-color="'+color+'"><span>'+color+'</span></button>');}list.innerHTML=items.join('');list.querySelectorAll('[data-color]').forEach(function(button){button.addEventListener('click',function(){copyValue(button.dataset.color);});});}
  function renderPalette(){var container=document.getElementById('palette');container.innerHTML=palette.length?palette.map(function(color){return '<button class="palette-chip" style="background:'+color+'" data-color="'+color+'"><span>'+color+'</span></button>';}).join(''):'<div class="palette-empty">Add colors from the picker.</div>';document.getElementById('copy-image').disabled=!palette.length;container.querySelectorAll('[data-color]').forEach(function(button){button.addEventListener('click',function(){copyValue(button.dataset.color);});});}
  function copyValue(value){navigator.clipboard&&navigator.clipboard.writeText(value);document.getElementById('copy-status').textContent=value+' copied to clipboard.';}
  function copyPaletteImage(){if(!palette.length){document.getElementById('copy-status').textContent='Add colors first.';return;}var paletteElement=document.getElementById('palette');if(!window.htmlToImage){document.getElementById('copy-status').textContent='Image capture is unavailable.';return;}htmlToImage.toBlob(paletteElement,{pixelRatio:2,backgroundColor:'#ffffff'}).then(function(blob){if(!blob)throw new Error('Empty palette image');if(navigator.clipboard&&window.ClipboardItem){return navigator.clipboard.write([new ClipboardItem({'image/png':blob})]).then(function(){document.getElementById('copy-status').textContent='Palette image copied to clipboard.';});}throw new Error('Clipboard image is unavailable');}).catch(function(){htmlToImage.toBlob(paletteElement,{pixelRatio:2,backgroundColor:'#ffffff'}).then(downloadPaletteImage).catch(function(){document.getElementById('copy-status').textContent='Could not create palette image.';});});}
  function downloadPaletteImage(blob){var link=document.createElement('a');link.download='color-palette.png';link.href=URL.createObjectURL(blob);link.click();setTimeout(function(){URL.revokeObjectURL(link.href);},1000);document.getElementById('copy-status').textContent='Clipboard unavailable. Palette downloaded as PNG.';}
  function extractColors(image){var canvas=document.createElement('canvas'),size=240,ctx=canvas.getContext('2d');canvas.width=size;canvas.height=size;ctx.drawImage(image,0,0,size,size);var data=ctx.getImageData(0,0,size,size).data,pixels=[];for(var i=0;i<data.length;i+=4){if(data[i+3]>=128)pixels.push([data[i],data[i+1],data[i+2]]);}if(!pixels.length){extracted=[];renderExtracted();return;}var clusterCount=Math.min(15,pixels.length),centers=[];for(var c=0;c<clusterCount;c+=1)centers.push(pixels[Math.floor(c*pixels.length/clusterCount)].slice());for(var round=0;round<7;round+=1){var sums=centers.map(function(){return{r:0,g:0,b:0,count:0};});pixels.forEach(function(pixel){var nearest=0,best=Infinity;centers.forEach(function(center,index){var dr=pixel[0]-center[0],dg=pixel[1]-center[1],db=pixel[2]-center[2],distance=dr*dr+dg*dg+db*db;if(distance<best){best=distance;nearest=index;}});var sum=sums[nearest];sum.r+=pixel[0];sum.g+=pixel[1];sum.b+=pixel[2];sum.count+=1;});centers=centers.map(function(center,index){var sum=sums[index];return sum.count? [sum.r/sum.count,sum.g/sum.count,sum.b/sum.count]:center;});}var counts=centers.map(function(){return{r:0,g:0,b:0,count:0};});pixels.forEach(function(pixel){var nearest=0,best=Infinity;centers.forEach(function(center,index){var dr=pixel[0]-center[0],dg=pixel[1]-center[1],db=pixel[2]-center[2],distance=dr*dr+dg*dg+db*db;if(distance<best){best=distance;nearest=index;}});var sum=counts[nearest];sum.r+=pixel[0];sum.g+=pixel[1];sum.b+=pixel[2];sum.count+=1;});extracted=counts.filter(function(bucket){return bucket.count>0;}).sort(function(a,b){return b.count-a.count;}).map(function(bucket){var rgb={r:Math.round(bucket.r/bucket.count),g:Math.round(bucket.g/bucket.count),b:Math.round(bucket.b/bucket.count)};return{hex:rgbToHex(rgb),rgb:rgb,hsl:rgbToHsl(rgb),count:bucket.count,percentage:Math.round(bucket.count/pixels.length*1000)/10};});renderExtracted();}
  function renderExtracted(){var visible=extracted.filter(function(color){return color.percentage>0;});var list=document.getElementById('extracted-colors');list.innerHTML=visible.length?visible.map(function(color){return'<button class="extracted-color" data-color="'+color.hex+'"><span class="extracted-swatch" style="background:'+color.hex+'"></span><p class="extracted-hex">'+color.hex+' <small>'+color.percentage+'%</small></p><p class="extracted-values">RGB '+color.rgb.r+', '+color.rgb.g+', '+color.rgb.b+'<br>HSL '+color.hsl.h+'°, '+color.hsl.s+'%, '+color.hsl.l+'%</p></button>';}).join(''):'<div class="palette-empty extracted-empty">Upload an image to analyze its colors.</div>';document.getElementById('add-extracted').disabled=!visible.length;list.querySelectorAll('[data-color]').forEach(function(button){button.addEventListener('click',function(){setColor(button.dataset.color);});});}
  picker.addEventListener('input',function(){setColor(picker.value);});
  hexInput.addEventListener('change',function(){setColor(hexInput.value.trim());});
  document.getElementById('add-color').addEventListener('click',function(){if(!palette.includes(picker.value.toUpperCase()))palette.push(picker.value.toUpperCase());renderPalette();});
  document.querySelectorAll('[data-copy]').forEach(function(button){button.addEventListener('click',function(){copyValue(button.textContent);});});
  document.getElementById('copy-css').addEventListener('click',function(){var css=palette.map(function(color,index){return'--color-'+(index+1)+': '+color+';';}).join('\n');copyValue(css||'Add colors first.');});
  document.getElementById('copy-image').addEventListener('click',copyPaletteImage);
  document.querySelectorAll('.color-tab').forEach(function(tab){tab.addEventListener('click',function(){document.querySelectorAll('.color-tab').forEach(function(item){item.classList.toggle('active',item===tab);});document.querySelectorAll('.color-panel').forEach(function(panel){panel.classList.toggle('active',panel.id===tab.dataset.panel);});});});
  document.getElementById('palette-image').addEventListener('change',function(){var file=this.files[0];if(!file)return;var url=URL.createObjectURL(file),image=new Image();image.onload=function(){var preview=document.getElementById('palette-image-preview');preview.innerHTML='';var previewImage=document.createElement('img');previewImage.src=url;previewImage.alt=file.name;preview.appendChild(previewImage);preview.classList.add('visible');extractColors(image);};image.src=url;});
  document.getElementById('add-extracted').addEventListener('click',function(){extracted.forEach(function(color){if(!palette.includes(color.hex))palette.push(color.hex);});renderPalette();});
  setColor(picker.value);
}());
