(function(){
  'use strict';
  var input=document.getElementById('qa-input'),files=[],records=[],presets={
    'instagram-square':[1080,1080],'instagram-portrait':[1080,1350],story:[1080,1920],linkedin:[1200,627],presentation:[1920,1080],a4:[2480,3508]
  };
  function sizeLabel(bytes){return(bytes/1024/1024).toFixed(2)+' MB';}
  function selectedSize(){var preset=document.getElementById('qa-preset').value;return presets[preset]||[Number(document.getElementById('qa-width').value),Number(document.getElementById('qa-height').value)];}
  function readFiles(selected){files=[];Array.from(selected).forEach(function(file){if(!/^image\/(png|jpeg|webp)$/.test(file.type))return;var image=new Image();image.onload=function(){files.push({file:file,image:image});document.getElementById('qa-summary').textContent=files.length+' asset'+(files.length===1?'':'s')+' selected';document.getElementById('qa-check').disabled=false;};image.src=URL.createObjectURL(file);});}
  function check(entry){var size=selectedSize(),file=entry.file,image=entry.image,ratio=size[0]/size[1],actualRatio=image.naturalWidth/image.naturalHeight,ratioDiff=Math.abs(actualRatio-ratio)/ratio,format=/image\/(png|jpeg|webp)/.test(file.type),nameOk=/^[a-z0-9][a-z0-9._-]*$/.test(file.name),sizeLimit=Number(document.getElementById('qa-max-size').value)*1024*1024;var rules=[{label:'Dimensions '+image.naturalWidth+'×'+image.naturalHeight,kind:image.naturalWidth>=size[0]&&image.naturalHeight>=size[1]?'pass':'fail'},{label:'Ratio '+actualRatio.toFixed(2),kind:ratioDiff<=.03?'pass':ratioDiff<=.12?'warning':'fail'},{label:'Format '+file.type.split('/')[1].toUpperCase(),kind:format?'pass':'fail'},{label:'Size '+sizeLabel(file.size),kind:file.size<=sizeLimit?'pass':'warning'},{label:'Filename',kind:nameOk?'pass':'warning'}];var failed=rules.filter(function(rule){return rule.kind==='fail'}).length,warnings=rules.filter(function(rule){return rule.kind==='warning'}).length;return{name:file.name,status:failed?'FAIL':warnings?'WARNING':'PASS',statusClass:failed?'fail':warnings?'warning':'pass',meta:image.naturalWidth+' × '+image.naturalHeight+' px · '+sizeLabel(file.size),rules:rules};}
  function render(){var list=document.getElementById('qa-list');list.innerHTML=records.length?records.map(function(record){return '<article class="qa-item"><div class="qa-item-head"><p class="qa-file" title="'+record.name+'">'+record.name+'</p><span class="qa-status '+record.statusClass+'">'+record.status+'</span></div><p class="qa-meta">'+record.meta+'</p><div class="qa-rules">'+record.rules.map(function(rule){return '<span class="qa-rule '+rule.kind+'">'+rule.label+'</span>';}).join('')+'</div></article>';}).join(''):'<div class="empty-state">Your QA results will appear here.</div>';document.getElementById('qa-export').disabled=!records.length;}
  input.addEventListener('change',function(){readFiles(input.files);});
  document.getElementById('qa-preset').addEventListener('change',function(){document.getElementById('qa-custom').hidden=this.value!=='custom';});
  document.getElementById('qa-max-size').addEventListener('input',function(){document.getElementById('qa-size-value').textContent=this.value+' MB';});
  document.getElementById('qa-check').addEventListener('click',function(){records=files.map(check);render();});
  document.getElementById('qa-clear').addEventListener('click',function(){files=[];records=[];input.value='';document.getElementById('qa-summary').textContent='No assets selected';document.getElementById('qa-check').disabled=true;render();});
  document.getElementById('qa-export').addEventListener('click',function(){var rows=[['File','Status','Metadata','Rules']].concat(records.map(function(record){return[record.name,record.status,record.meta,record.rules.map(function(rule){return rule.label+': '+rule.kind.toUpperCase();}).join(' | ')];}));var csv=rows.map(function(row){return row.map(function(value){return'"'+String(value).replace(/"/g,'""')+'"';}).join(',');}).join('\r\n');var link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='design-qa-report.csv';link.click();});
}());
