(function(){
  'use strict';
  var input=document.getElementById('pdf-input'),files=[],mergedBytes=null,previewUrl='';
  function size(bytes){return(bytes/1024/1024).toFixed(2)+' MB';}
  function render(){var list=document.getElementById('pdf-list'),status=document.getElementById('pdf-status');document.getElementById('pdf-summary').textContent=files.length?files.length+' PDF'+(files.length===1?'':'s')+' selected':'No PDFs selected';document.getElementById('merge-pdf').disabled=!files.length;list.innerHTML=files.length?files.map(function(entry,index){return'<li class="pdf-item"><span class="pdf-item-number">'+(index+1)+'</span><span class="pdf-item-name" title="'+entry.file.name+'">'+entry.file.name+'</span><span class="pdf-item-size">'+size(entry.file.size)+'</span><button class="pdf-remove" data-index="'+index+'" type="button">×</button></li>';}).join(''):'<li class="pdf-empty">Your PDF files will appear here.</li>';if(status&&!mergedBytes)status.textContent=files.length===1?'PDF loaded. Click Merge & Preview to preview it.':'Ready to merge '+files.length+' PDFs. File order is preserved.';list.querySelectorAll('.pdf-remove').forEach(function(button){button.addEventListener('click',function(){files.splice(Number(button.dataset.index),1);mergedBytes=null;document.getElementById('download-pdf').disabled=true;render();});});}
  function read(selected){var chosen=Array.prototype.slice.call(selected||[]),valid=chosen.filter(function(file){return file.type==='application/pdf'||/\.pdf$/i.test(file.name);});files=valid;render();if(valid.length){showInputPreview(valid[0].file);}else if(chosen.length)document.getElementById('pdf-status').textContent='No PDF files detected. Choose files ending in .pdf.';}
  function showInputPreview(file){var url=URL.createObjectURL(file);document.getElementById('pdf-preview').innerHTML='<iframe title="Selected PDF preview" src="'+url+'"></iframe>';document.getElementById('download-pdf').disabled=true;}
  async function merge(){if(!window.PDFLib||!files.length)return;var status=document.getElementById('pdf-status'),merged=await PDFLib.PDFDocument.create();status.textContent=files.length===1?'Reading PDF...':'Reading and combining pages...';for(var i=0;i<files.length;i+=1){var source=await PDFLib.PDFDocument.load(await files[i].arrayBuffer());var pages=await merged.copyPages(source,source.getPageIndices());pages.forEach(function(page){merged.addPage(page);});}mergedBytes=await merged.save({useObjectStreams:document.getElementById('compress-pdf').checked,addDefaultPage:false});if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(new Blob([mergedBytes],{type:'application/pdf'}));document.getElementById('pdf-preview').innerHTML='<iframe title="Merged PDF preview" src="'+previewUrl+'"></iframe>';document.getElementById('download-pdf').disabled=false;status.textContent=(files.length===1?'Preview ready · 1 PDF processed':'Preview ready · '+files.length+' PDFs combined')+' · '+size(mergedBytes.length)+' output';}
  function download(){if(!mergedBytes)return;var name=document.getElementById('output-name').value.trim()||'merged-document.pdf';if(!/\.pdf$/i.test(name))name+='.pdf';var link=document.createElement('a');link.download=name;link.href=previewUrl;link.click();}
  input.addEventListener('change',function(){read(input.files);});document.getElementById('clear-pdfs').addEventListener('click',function(){files=[];mergedBytes=null;input.value='';if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';document.getElementById('pdf-preview').innerHTML='<span>Preview appears after merge.</span>';document.getElementById('download-pdf').disabled=true;render();});document.getElementById('merge-pdf').addEventListener('click',merge);document.getElementById('download-pdf').addEventListener('click',download);render();
}());
