(function(){
  'use strict';
  var input=document.getElementById('pdf-input'),files=[],mergedBytes=null,previewUrl='';
  function size(bytes){return(bytes/1024/1024).toFixed(2)+' MB';}
  function render(){var list=document.getElementById('pdf-list'),status=document.getElementById('pdf-status');document.getElementById('pdf-summary').textContent=files.length?files.length+' PDF'+(files.length===1?'':'s')+' selected':'No PDFs selected';list.innerHTML=files.length?files.map(function(entry,index){return'<li class="pdf-item"><span class="pdf-item-number">'+(index+1)+'</span><span class="pdf-item-name" title="'+entry.file.name+'">'+entry.file.name+'</span><span class="pdf-item-size">'+size(entry.file.size)+'</span><button class="pdf-remove" data-index="'+index+'" type="button">×</button></li>';}).join(''):'<li class="pdf-empty">Your PDF files will appear here.</li>';if(status&&!mergedBytes)status.textContent=files.length?'Preparing preview...':'Add a PDF file to begin.';list.querySelectorAll('.pdf-remove').forEach(function(button){button.addEventListener('click',function(){files.splice(Number(button.dataset.index),1);mergedBytes=null;document.getElementById('download-pdf').disabled=true;render();if(files.length)merge();});});}
  function read(selected){var chosen=Array.prototype.slice.call(selected||[]),valid=chosen.filter(function(file){return file.type==='application/pdf'||/\.pdf$/i.test(file.name);});var added=0;valid.forEach(function(file){var duplicate=files.some(function(entry){return entry.file.name===file.name&&entry.file.size===file.size&&entry.file.lastModified===file.lastModified;});if(!duplicate){files.push({file:file});added+=1;}});render();if(added){merge();}else if(chosen.length)document.getElementById('pdf-status').textContent='Those PDFs are already in the queue.';}
  async function merge(){if(!window.PDFLib||!files.length)return;var status=document.getElementById('pdf-status'),merged=await PDFLib.PDFDocument.create();status.textContent=files.length===1?'Reading PDF...':'Reading and combining pages...';try{for(var i=0;i<files.length;i+=1){var source=await PDFLib.PDFDocument.load(await files[i].file.arrayBuffer());var pages=await merged.copyPages(source,source.getPageIndices());pages.forEach(function(page){merged.addPage(page);});}mergedBytes=await merged.save({useObjectStreams:document.getElementById('compress-pdf').checked,addDefaultPage:false});if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(new Blob([mergedBytes],{type:'application/pdf'}));document.getElementById('pdf-preview').innerHTML='<iframe title="Merged PDF preview" src="'+previewUrl+'"></iframe>';document.getElementById('download-pdf').disabled=false;status.textContent=(files.length===1?'Preview ready · 1 PDF processed':'Preview ready · '+files.length+' PDFs combined')+' · '+size(mergedBytes.length)+' output';}catch(error){mergedBytes=null;document.getElementById('download-pdf').disabled=true;status.textContent=/encrypted/i.test(error.message||'')?'Cannot preview an encrypted PDF. Remove it or unlock it before merging.':'Could not read this PDF: '+(error.message||'Unknown error');}}
  function download(){if(!mergedBytes)return;var name=document.getElementById('output-name').value.trim()||'merged-document.pdf';if(!/\.pdf$/i.test(name))name+='.pdf';var link=document.createElement('a');link.download=name;link.href=previewUrl;link.click();}
  input.addEventListener('change',function(){read(input.files);});document.getElementById('clear-pdfs').addEventListener('click',function(){files=[];mergedBytes=null;input.value='';if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';document.getElementById('pdf-preview').innerHTML='<span>Preview appears after merge.</span>';document.getElementById('download-pdf').disabled=true;render();});document.getElementById('compress-pdf').addEventListener('change',function(){if(files.length)merge();});document.getElementById('download-pdf').addEventListener('click',download);render();
}());
