(function(){
  'use strict';
  var input=document.getElementById('board-input'),stage=document.getElementById('board-stage'),files=[];
  function escapeHtml(value){return String(value).replace(/[&<>"']/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char];});}
  function render(){var title=document.getElementById('board-title').value.trim(),subtitle=document.getElementById('board-subtitle').value.trim(),columns=document.getElementById('board-columns').value,gap=document.getElementById('board-gap').value,background=document.getElementById('board-background').value,captions=document.getElementById('show-captions').checked;document.getElementById('gap-value').textContent=gap+' px';document.getElementById('board-size').textContent=files.length+' image'+(files.length===1?'':'s');if(!files.length){stage.innerHTML='<div class="board-empty">Upload images to build your board.</div>';document.getElementById('export-png').disabled=true;document.getElementById('export-pdf').disabled=true;return;}stage.innerHTML='<div id="board-sheet" class="board-sheet" style="background:'+background+'"><header class="board-sheet-header">'+(title?'<h3 class="board-sheet-title">'+escapeHtml(title)+'</h3>':'')+(subtitle?'<p class="board-sheet-subtitle">'+escapeHtml(subtitle)+'</p>':'')+'</header><div class="board-items" style="grid-template-columns:repeat('+columns+',minmax(0,1fr));--board-gap:'+gap+'px">'+files.map(function(entry,index){return'<figure class="board-item"><img src="'+entry.url+'" alt="'+escapeHtml(entry.label)+'">'+(captions?'<input class="board-caption-input" data-file-index="'+index+'" value="'+escapeHtml(entry.label)+'" aria-label="Image '+(index+1)+' name"><div class="board-caption-output">'+escapeHtml(entry.label)+'</div>':'')+'</figure>';}).join('')+'</div></div>';stage.querySelectorAll('.board-caption-input').forEach(function(field){var output=field.nextElementSibling;field.style.display='none';output.style.display='block';field.addEventListener('input',function(){var entry=files[Number(field.dataset.fileIndex)];entry.label=field.value;output.textContent=field.value;});field.addEventListener('focus',function(){field.style.display='block';output.style.display='none';});field.addEventListener('blur',function(){field.style.display='none';output.style.display='block';});});stage.querySelectorAll('.board-caption-output').forEach(function(output){output.addEventListener('click',function(){var field=output.previousElementSibling;field.style.display='block';output.style.display='none';field.focus();field.select();});});document.getElementById('export-png').disabled=false;document.getElementById('export-pdf').disabled=false;}
  function readFiles(selected){files=[];Array.from(selected).forEach(function(file){if(!/^image\/(png|jpeg|webp)$/.test(file.type))return;var url=URL.createObjectURL(file),image=new Image();image.onload=function(){files.push({file:file,label:file.name.replace(/\.[^.]+$/,''),url:url,image:image});document.getElementById('board-summary').textContent=files.length+' image'+(files.length===1?'':'s')+' selected';render();};image.src=url;});}
  async function exportBoard(format){var node=document.getElementById('board-sheet');if(!node)return;var fields=node.querySelectorAll('.board-caption-input'),outputs=node.querySelectorAll('.board-caption-output');fields.forEach(function(field){field.style.display='none';});outputs.forEach(function(output){output.style.display='block';});try{var dataUrl=await htmlToImage.toPng(node,{pixelRatio:2,backgroundColor:document.getElementById('board-background').value});if(format==='png'){var link=document.createElement('a');link.download='presentation-board.png';link.href=dataUrl;link.click();return;}var image=await PDFLib.PDFDocument.create(),png=await image.embedPng(dataUrl),page=image.addPage([png.width,png.height]);page.drawImage(png,{x:0,y:0,width:png.width,height:png.height});var pdfLink=document.createElement('a');pdfLink.download='presentation-board.pdf';pdfLink.href=URL.createObjectURL(new Blob([await image.save()],{type:'application/pdf'}));pdfLink.click();}finally{fields.forEach(function(field){field.style.display='block';});outputs.forEach(function(output){output.style.display='none';});}}
  input.addEventListener('change',function(){readFiles(input.files);});document.querySelectorAll('.board-options input,.board-options select').forEach(function(control){control.addEventListener('input',render);control.addEventListener('change',render);});document.getElementById('export-png').addEventListener('click',function(){exportBoard('png');});document.getElementById('export-pdf').addEventListener('click',function(){exportBoard('pdf');});render();
}());
