(function(){
  'use strict';
  var sizes=[
    {platform:'Instagram',format:'Post Square',usage:'Feed',width:1080,height:1080,aliases:['square','post','feed']},
    {platform:'Instagram',format:'Post Portrait',usage:'Feed',width:1080,height:1350,aliases:['portrait','post','feed']},
    {platform:'Instagram',format:'Post Landscape',usage:'Feed',width:1080,height:566,aliases:['landscape','post','feed']},
    {platform:'Instagram',format:'Story / Reel',usage:'Story and video',width:1080,height:1920,maxHeight:1920,aliases:['story','reels','vertical']},
    {platform:'Instagram',format:'Profile Photo',usage:'Avatar',width:320,height:320,aliases:['profile','avatar']},
    {platform:'Instagram',format:'Highlight Cover',usage:'Highlight',width:1080,height:1920,aliases:['highlight','story']},
    {platform:'WhatsApp',format:'WA Status',usage:'Status',width:1080,height:1920,maxHeight:1920,aliases:['status','vertical']},
    {platform:'WhatsApp',format:'WA Blast',usage:'Image message',width:1080,height:1080,maxHeight:1080,aliases:['blast','message','square']},
    {platform:'WhatsApp',format:'WA Blast Portrait',usage:'Image message',width:1080,height:1350,maxHeight:1350,aliases:['blast','message','portrait']},
    {platform:'WhatsApp',format:'WA Blast Landscape',usage:'Image message',width:1280,height:720,maxHeight:720,aliases:['blast','message','landscape']},
    {platform:'WhatsApp',format:'WA Profile Photo',usage:'Avatar',width:500,height:500,aliases:['profile','avatar']},
    {platform:'WhatsApp',format:'WA Catalog',usage:'Product image',width:800,height:800,aliases:['catalog','product']},
    {platform:'TikTok',format:'Video',usage:'Video',width:1080,height:1920,maxHeight:1920,aliases:['video','vertical']},
    {platform:'TikTok',format:'Profile Photo',usage:'Avatar',width:200,height:200,aliases:['profile','avatar']},
    {platform:'LinkedIn',format:'Post Landscape',usage:'Feed',width:1200,height:627,aliases:['landscape','post','feed']},
    {platform:'LinkedIn',format:'Post Square',usage:'Feed',width:1200,height:1200,aliases:['square','post','feed']},
    {platform:'LinkedIn',format:'Post Portrait',usage:'Feed',width:1080,height:1350,aliases:['portrait','post','feed']},
    {platform:'LinkedIn',format:'Profile Banner',usage:'Personal profile',width:1584,height:396,aliases:['banner','profile']},
    {platform:'LinkedIn',format:'Company Cover',usage:'Company page',width:1128,height:191,aliases:['cover','company']},
    {platform:'YouTube',format:'Thumbnail',usage:'Video cover',width:1280,height:720,aliases:['thumbnail','landscape']},
    {platform:'YouTube',format:'Channel Banner',usage:'Channel art',width:2560,height:1440,aliases:['banner','channel']},
    {platform:'YouTube',format:'Shorts',usage:'Short video',width:1080,height:1920,maxHeight:1920,aliases:['shorts','vertical']},
    {platform:'Facebook',format:'Post Landscape',usage:'Feed',width:1200,height:630,aliases:['landscape','post','feed']},
    {platform:'Facebook',format:'Post Square',usage:'Feed',width:1200,height:1200,aliases:['square','post','feed']},
    {platform:'Facebook',format:'Story',usage:'Story',width:1080,height:1920,maxHeight:1920,aliases:['story','vertical']},
    {platform:'Facebook',format:'Page Cover',usage:'Cover',width:1640,height:856,aliases:['cover','page']},
    {platform:'X / Twitter',format:'Post Landscape',usage:'Feed',width:1600,height:900,aliases:['twitter','landscape','post']},
    {platform:'X / Twitter',format:'Header Banner',usage:'Profile',width:1500,height:500,aliases:['twitter','banner','profile']},
  ];
  var activePlatform='all';
  function ratio(w,h){var a=w,b=h;while(b){var t=a%b;a=b;b=t;}return(w/a)+':'+(h/a);}
  function copy(value){if(navigator.clipboard)navigator.clipboard.writeText(value);}
  function templateMargins(item){var story=item.usage.toLowerCase().includes('story')||item.aliases&&item.aliases.includes('vertical');return{left:Math.round(item.width*.08),right:Math.round(item.width*.08),top:story?155:Math.round(item.height*.06),bottom:story?155:Math.round(item.height*.06),danger:story?155:0,story:story};}
  function downloadTemplate(item){var canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),m=templateMargins(item);canvas.width=item.width;canvas.height=item.height;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,item.width,item.height);ctx.strokeStyle='#db0011';ctx.lineWidth=Math.max(2,Math.round(item.width/540));ctx.setLineDash([Math.max(8,Math.round(item.width/60)),Math.max(5,Math.round(item.width/100))]);ctx.strokeRect(m.left,m.top,item.width-m.left-m.right,item.height-m.top-m.bottom);ctx.setLineDash([]);ctx.fillStyle='#db0011';ctx.font='700 '+Math.max(18,Math.round(item.width/54))+'px Arial';ctx.textAlign='center';ctx.fillText(m.story?'SAFE AREA · '+item.width+' × '+(item.height-m.top-m.bottom)+' px':'SAFE AREA',item.width/2,m.top+Math.max(28,Math.round(item.height/45)));if(m.danger){ctx.fillStyle='rgba(219,0,17,.11)';ctx.fillRect(0,0,item.width,m.danger);ctx.fillRect(0,item.height-m.danger,item.width,m.danger);ctx.fillStyle='#db0011';ctx.font='700 '+Math.max(16,Math.round(item.width/68))+'px Arial';ctx.fillText('TOP MARGIN · '+m.top+' px',item.width/2,m.top/2-18);ctx.font='500 '+Math.max(12,Math.round(item.width/90))+'px Arial';ctx.fillText('Username, profile picture, timestamp, and close button appear here.',item.width/2,m.top/2+12);ctx.font='700 '+Math.max(16,Math.round(item.width/68))+'px Arial';ctx.fillText('BOTTOM MARGIN · '+m.bottom+' px',item.width/2,item.height-m.bottom/2-18);ctx.font='500 '+Math.max(12,Math.round(item.width/90))+'px Arial';ctx.fillText('Reply bar, message input, and interactive stickers cover this area.',item.width/2,item.height-m.bottom/2+12);}ctx.fillStyle='#71808c';ctx.font='500 '+Math.max(14,Math.round(item.width/90))+'px Arial';ctx.textAlign='left';ctx.fillText(item.width+' × '+item.height+' px · '+item.format,m.left,m.top+Math.max(50,Math.round(item.height/28)));var link=document.createElement('a');link.download='template-'+item.platform.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+item.width+'x'+item.height+'.png';link.href=canvas.toDataURL('image/png');link.click();}
  function render(){var query=document.getElementById('size-search').value.toLowerCase(),grid=document.getElementById('size-grid');var filtered=sizes.filter(function(item){return(activePlatform==='all'||item.platform===activePlatform)&&(!query||(item.platform+' '+item.format+' '+item.usage+' '+(item.aliases||[]).join(' ')).toLowerCase().includes(query));});grid.innerHTML=filtered.length?filtered.map(function(item){var margins=templateMargins(item),safeHeight=item.height-margins.top-margins.bottom;return'<article class="size-card"><div class="size-card-top"><span class="platform-label">'+item.platform+'</span><span class="usage-label">'+item.usage+'</span></div><h2>'+item.format+'</h2><div class="size-number" title="Click a number to copy"><button class="size-part" data-value="'+item.width+' px">'+item.width+'</button><span>×</span><button class="size-part" data-value="'+item.height+' px">'+item.height+'</button><small>px</small></div><div class="size-meta"><span>Ratio '+ratio(item.width,item.height)+'</span><span>Safe L/R '+margins.left+' px</span>'+(margins.story?'<span class="max-height">Safe area '+item.width+' × '+safeHeight+' px</span>':'')+(margins.danger?'<span class="max-height">Danger top/bottom '+margins.danger+' px</span>':'')+(item.maxHeight?'<span class="max-height">Max height '+item.maxHeight+' px</span>':'')+'</div><div class="size-actions"><button class="copy-size" data-value="'+item.width+' × '+item.height+' px">Copy size</button><button class="download-template" data-index="'+sizes.indexOf(item)+'">Download template</button></div></article>';}).join(''):'<div class="no-results">No matching sizes.</div>';grid.querySelectorAll('.copy-size,.size-part').forEach(function(button){button.addEventListener('click',function(){copy(button.dataset.value);var original=button.textContent;button.textContent='Copied';setTimeout(function(){button.textContent=original;},1200);});});grid.querySelectorAll('.download-template').forEach(function(button){button.addEventListener('click',function(){downloadTemplate(sizes[Number(button.dataset.index)]);});});}
  document.querySelectorAll('.filter-button').forEach(function(button){button.addEventListener('click',function(){activePlatform=button.dataset.platform;document.querySelectorAll('.filter-button').forEach(function(item){item.classList.toggle('active',item===button);});render();});});
  document.getElementById('size-search').addEventListener('input',render);
  function updateCustom(){var w=Number(document.getElementById('custom-width').value)||1,h=Number(document.getElementById('custom-height').value)||1;document.getElementById('custom-ratio').textContent='Ratio '+ratio(w,h);}
  document.getElementById('custom-width').addEventListener('input',updateCustom);document.getElementById('custom-height').addEventListener('input',updateCustom);document.getElementById('copy-custom').addEventListener('click',function(){var w=document.getElementById('custom-width').value,h=document.getElementById('custom-height').value;copy(w+' × '+h+' px');this.textContent='Copied';setTimeout(function(){document.getElementById('copy-custom').textContent='Copy size';},1200);});
  render();
}());
