(function(){'use strict';
var sizes=[
{platform:'Instagram',format:'Post Square',usage:'Feed',width:1080,height:1080,aliases:['square','post'],note:'Keep important text away from the outer edges.'},
{platform:'Instagram',format:'Post Portrait',usage:'Feed',width:1080,height:1350,aliases:['portrait','post'],note:'Recommended portrait feed format.'},
{platform:'Instagram',format:'Story / Reel',usage:'Story',width:1080,height:1920,maxHeight:1920,safe:{top:155,bottom:155},aliases:['story','reels','vertical'],note:'Top and bottom UI can cover important content.'},
{platform:'Instagram',format:'Profile Photo',usage:'Profile',width:320,height:320,aliases:['avatar','profile']},
{platform:'WhatsApp',format:'WA Status',usage:'Story',width:1080,height:1920,maxHeight:1920,safe:{top:155,bottom:155},aliases:['status','vertical'],note:'Keep text inside the centered safe area.'},
{platform:'WhatsApp',format:'WA Blast',usage:'Messaging',width:1080,height:1080,maxHeight:1080,aliases:['blast','message','square'],note:'Tall images may be cropped in chat preview.'},
{platform:'WhatsApp',format:'WA Blast Portrait',usage:'Messaging',width:1080,height:1350,maxHeight:1350,aliases:['blast','message','portrait'],note:'Keep the main message centered.'},
{platform:'WhatsApp',format:'WA Blast Landscape',usage:'Messaging',width:1280,height:720,maxHeight:720,aliases:['blast','message','landscape']},
{platform:'TikTok',format:'Video',usage:'Video',width:1080,height:1920,maxHeight:1920,safe:{top:155,bottom:280},aliases:['vertical','reels'],note:'Top, bottom, and right UI can cover content.'},
{platform:'TikTok',format:'Profile Photo',usage:'Profile',width:200,height:200,aliases:['avatar','profile']},
{platform:'LinkedIn',format:'Post Landscape',usage:'Feed',width:1200,height:627,aliases:['landscape','post']},
{platform:'LinkedIn',format:'Post Square',usage:'Feed',width:1200,height:1200,aliases:['square','post']},
{platform:'LinkedIn',format:'Post Portrait',usage:'Feed',width:1080,height:1350,aliases:['portrait','post']},
{platform:'LinkedIn',format:'Profile Banner',usage:'Banner',width:1584,height:396,aliases:['profile','banner'],note:'Keep important content away from the profile overlap area.'},
{platform:'LinkedIn',format:'Company Cover',usage:'Cover',width:1128,height:191,aliases:['company','cover']},
{platform:'YouTube',format:'Thumbnail',usage:'Feed',width:1280,height:720,aliases:['thumbnail','landscape']},
{platform:'YouTube',format:'Channel Banner',usage:'Banner',width:2560,height:1440,aliases:['channel','banner']},
{platform:'YouTube',format:'Shorts',usage:'Video',width:1080,height:1920,maxHeight:1920,safe:{top:155,bottom:280},aliases:['vertical','shorts']},
{platform:'Facebook',format:'Post Landscape',usage:'Feed',width:1200,height:630,aliases:['landscape','post']},
{platform:'Facebook',format:'Post Square',usage:'Feed',width:1200,height:1200,aliases:['square','post']},
{platform:'Facebook',format:'Story',usage:'Story',width:1080,height:1920,maxHeight:1920,safe:{top:155,bottom:155},aliases:['vertical','story']},
{platform:'Facebook',format:'Page Cover',usage:'Cover',width:1640,height:856,aliases:['cover','page']},
{platform:'X / Twitter',format:'Post Landscape',usage:'Feed',width:1600,height:900,aliases:['twitter','landscape','post']},
{platform:'X / Twitter',format:'Header Banner',usage:'Banner',width:1500,height:500,aliases:['twitter','banner','profile']}
];
var activePlatform='all',favorites=JSON.parse(localStorage.getItem('epsilon-size-favorites')||'[]'),favoritesOnly=false;
var platformOrder=['all','Instagram','WhatsApp','TikTok','LinkedIn','YouTube','Facebook','X / Twitter'];
function ratio(w,h){var a=w,b=h;while(b){var t=a%b;a=b;b=t;}return(w/a)+':'+(h/a);}
function copy(value){if(navigator.clipboard)navigator.clipboard.writeText(value);}
function margins(item){var story=item.safe;return{left:Math.round(item.width*.08),right:Math.round(item.width*.08),top:story?story.top:Math.round(item.height*.06),bottom:story?story.bottom:Math.round(item.height*.06)};}
function isFavorite(item){return favorites.includes(item.platform+'|'+item.format);}
function toggleFavorite(item){var key=item.platform+'|'+item.format;if(isFavorite(item))favorites=favorites.filter(function(value){return value!==key;});else favorites.push(key);localStorage.setItem('epsilon-size-favorites',JSON.stringify(favorites));render();}
function template(item){var c=document.createElement('canvas'),x=c.getContext('2d'),m=margins(item);c.width=item.width;c.height=item.height;x.clearRect(0,0,c.width,c.height);x.strokeStyle='#db0011';x.lineWidth=Math.max(2,Math.round(item.width/540));x.setLineDash([Math.max(8,item.width/60),Math.max(5,item.width/100)]);x.strokeRect(m.left,m.top,c.width-m.left-m.right,c.height-m.top-m.bottom);x.setLineDash([]);x.fillStyle='#db0011';x.textAlign='center';x.font='700 '+Math.max(18,item.width/54)+'px Arial';x.fillText('SAFE AREA · '+item.width+' × '+(item.height-m.top-m.bottom)+' px',c.width/2,m.top+Math.max(28,item.height/45));if(item.safe){x.fillStyle='rgba(219,0,17,.11)';x.fillRect(0,0,c.width,m.top);x.fillRect(0,c.height-m.bottom,c.width,m.bottom);x.fillStyle='#db0011';x.font='700 '+Math.max(16,item.width/68)+'px Arial';x.fillText('DANGER ZONE · '+m.top+' px',c.width/2,m.top/2);x.fillText('DANGER ZONE · '+m.bottom+' px',c.width/2,c.height-m.bottom/2);}var link=document.createElement('a');link.download='template-'+item.platform.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+item.width+'x'+item.height+'.png';link.href=c.toDataURL('image/png');link.click();}
function render(){var query=document.getElementById('size-search').value.toLowerCase(),usage=document.getElementById('usage-filter').value,grid=document.getElementById('size-grid');var filtered=sizes.filter(function(item){var text=(item.platform+' '+item.format+' '+item.usage+' '+(item.aliases||[]).join(' ')).toLowerCase();return(activePlatform==='all'||item.platform===activePlatform)&&(usage==='all'||item.usage===usage)&&(!query||text.includes(query))&&(!favoritesOnly||isFavorite(item));});document.getElementById('result-count').textContent=filtered.length+' size'+(filtered.length===1?'':'s');grid.innerHTML=filtered.length?filtered.map(function(item){var m=margins(item),safeHeight=item.height-m.top-m.bottom,key=sizes.indexOf(item);return'<article class="size-card"><div class="size-card-top"><span class="platform-label">'+item.platform+'</span><button class="favorite-button '+(isFavorite(item)?'active':'')+'" data-favorite="'+key+'">★</button></div><h2>'+item.format+'</h2><div class="size-number"><button class="size-part" data-value="'+item.width+' px">'+item.width+'</button><span>×</span><button class="size-part" data-value="'+item.height+' px">'+item.height+'</button><small>px</small></div><div class="size-meta"><span>Ratio '+ratio(item.width,item.height)+'</span><span>Safe L/R '+m.left+' px</span>'+(item.safe?'<span class="max-height">Safe area '+item.width+' × '+safeHeight+' px</span>':'')+(item.safe?'<span class="max-height">Danger top/bottom '+m.top+' / '+m.bottom+' px</span>':'')+'</div>'+(item.note?'<p class="size-note">'+item.note+'</p>':'')+'<div class="size-actions"><button class="copy-size" data-value="'+item.width+' × '+item.height+' px">Copy size</button><button class="download-template" data-index="'+key+'">Download template</button></div><div class="copy-extra"><button data-extra="ratio" data-index="'+key+ '">'+ratio(item.width,item.height)+'</button><button data-extra="css" data-index="'+key+'">CSS</button><button data-extra="json" data-index="'+key+'">JSON</button></div></article>';}).join(''):'<div class="no-results">No matching sizes.</div>';grid.querySelectorAll('.size-part,.copy-size').forEach(function(button){button.addEventListener('click',function(){copy(button.dataset.value);});});grid.querySelectorAll('[data-favorite]').forEach(function(button){button.addEventListener('click',function(){toggleFavorite(sizes[Number(button.dataset.favorite)]);});});grid.querySelectorAll('.download-template').forEach(function(button){button.addEventListener('click',function(){template(sizes[Number(button.dataset.index)]);});});grid.querySelectorAll('[data-extra]').forEach(function(button){button.addEventListener('click',function(){var item=sizes[Number(button.dataset.index)],value=button.dataset.extra==='ratio'?ratio(item.width,item.height):button.dataset.extra==='css'?'width: '+item.width+'px; height: '+item.height+'px;':JSON.stringify(item,null,2);copy(value);});});}
function guideExport(format){var visible=sizes.filter(function(item){return activePlatform==='all'||item.platform===activePlatform;});if(format==='csv'){var csv='Platform,Format,Usage,Width,Height,Ratio,Note\n'+visible.map(function(item){return[item.platform,item.format,item.usage,item.width,item.height,ratio(item.width,item.height),item.note||''].map(function(v){return'"'+String(v).replace(/"/g,'""')+'"';}).join(',');}).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='social-size-guide.csv';a.click();return;}var sheet=document.createElement('div');sheet.style.cssText='width:1000px;padding:40px;background:#fff;color:#17212b;font:16px Arial';sheet.innerHTML='<h1>Social Size Guide</h1><p>'+activePlatform+' · reviewed September 2026</p><pre style="white-space:pre-wrap">'+visible.map(function(i){return i.platform+' · '+i.format+'\n'+i.width+' × '+i.height+' px · '+ratio(i.width,i.height);}).join('\n\n')+'</pre>';document.body.appendChild(sheet);htmlToImage.toPng(sheet,{pixelRatio:2}).then(function(data){if(format==='png'){var a=document.createElement('a');a.href=data;a.download='social-size-guide.png';a.click();}else{return PDFLib.PDFDocument.create().then(function(pdf){return pdf.embedPng(data).then(function(img){var page=pdf.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height});var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([pdf.save()],{type:'application/pdf'}));a.download='social-size-guide.pdf';a.click();});});}).finally(function(){sheet.remove();});}
document.querySelectorAll('.filter-button').forEach(function(button){button.addEventListener('click',function(){activePlatform=button.dataset.platform;document.querySelectorAll('.filter-button').forEach(function(item){item.classList.toggle('active',item===button);});render();});});document.getElementById('size-search').addEventListener('input',render);document.getElementById('usage-filter').addEventListener('change',render);document.getElementById('favorite-filter').addEventListener('click',function(){favoritesOnly=!favoritesOnly;this.classList.toggle('active',favoritesOnly);render();});document.getElementById('export-csv').addEventListener('click',function(){guideExport('csv');});document.getElementById('export-guide-png').addEventListener('click',function(){guideExport('png');});document.getElementById('export-guide-pdf').addEventListener('click',function(){guideExport('pdf');});function updateCustom(){var w=Number(document.getElementById('custom-width').value)||1,h=Number(document.getElementById('custom-height').value)||1;document.getElementById('custom-ratio').textContent='Ratio '+ratio(w,h);}document.getElementById('custom-width').addEventListener('input',updateCustom);document.getElementById('custom-height').addEventListener('input',updateCustom);document.getElementById('copy-custom').addEventListener('click',function(){var w=document.getElementById('custom-width').value,h=document.getElementById('custom-height').value;copy(w+' × '+h+' px');});render();
}());
