(function(){
  'use strict';
  var input=document.getElementById('canvas-input'),canvas=document.getElementById('social-canvas'),ctx=canvas.getContext('2d'),image=null,fileName='social-canvas';
  var presets={};
  function size(){var value=document.getElementById('canvas-preset').value;if(value==='custom')return[Number(document.getElementById('canvas-width').value)||1080,Number(document.getElementById('canvas-height').value)||1080];var parts=value.split('x');return[Number(parts[0]),Number(parts[1])];}
  function render(){var dimensions=size(),w=dimensions[0],h=dimensions[1];canvas.width=w;canvas.height=h;document.getElementById('canvas-size-label').textContent=w+' × '+h;ctx.fillStyle=document.getElementById('background').value;ctx.fillRect(0,0,w,h);if(!image){document.getElementById('preview-empty').style.display='block';return;}document.getElementById('preview-empty').style.display='none';var scale=document.getElementById('fit-mode').value==='cover'?Math.max(w/image.naturalWidth,h/image.naturalHeight):Math.min(w/image.naturalWidth,h/image.naturalHeight);scale*=Number(document.getElementById('zoom').value)/100;var drawW=image.naturalWidth*scale,drawH=image.naturalHeight*scale;var x=(w-drawW)*Number(document.getElementById('position-x').value)/100,y=(h-drawH)*Number(document.getElementById('position-y').value)/100;ctx.drawImage(image,x,y,drawW,drawH);var text=document.getElementById('overlay-text').value.trim();if(text){ctx.fillStyle=document.getElementById('text-color').value;ctx.font='700 '+Number(document.getElementById('text-size').value)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';text.split('\n').forEach(function(line,index){ctx.fillText(line,w/2,h*.82+index*Number(document.getElementById('text-size').value)*1.2);});}document.getElementById('export-png').disabled=false;document.getElementById('export-jpg').disabled=false;}
  function download(type){var link=document.createElement('a');link.download=fileName+'.'+(type==='image/jpeg'?'jpg':'png');link.href=canvas.toDataURL(type,.92);link.click();}
  input.addEventListener('change',function(){var file=input.files[0];if(!file)return;fileName=file.name.replace(/\.[^.]+$/,'');var url=URL.createObjectURL(file);image=new Image();image.onload=function(){document.getElementById('canvas-file').textContent=file.name;render();URL.revokeObjectURL(url);};image.src=url;});
  document.querySelectorAll('.canvas-options input,.canvas-options select,.canvas-options textarea').forEach(function(control){control.addEventListener('input',function(){if(control.id==='zoom')document.getElementById('zoom-value').textContent=control.value+'%';render();});control.addEventListener('change',function(){if(control.id==='canvas-preset')document.getElementById('canvas-custom').hidden=control.value!=='custom';render();});});
  document.getElementById('export-png').addEventListener('click',function(){download('image/png');});document.getElementById('export-jpg').addEventListener('click',function(){download('image/jpeg');});render();
}());
